---
apiVersion: v1
kind: Namespace
metadata:
  name: shell-project
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-app
  namespace: shell-project
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: node-app
  namespace: shell-project
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "get", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
---    
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: node-app
    namespace: shell-project